apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mendix-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mendix-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50 # CPU 사용률이 50%를 넘으면 파드를 추가합니다.
